### ISSUE TITLE
Jira import progress

### ISSUE THREAD

**Issue by indiealexh** [JetBrains/space-issues-import#4]
Looking to migrate from Jira to spaces, any progress on the Jira importer?

**Comment by w3cproject** [comment]
@indiealexh Hi!
As I can see, the repository owners are not particularly involved in the improvements.
I am already working on an improved version of importing tasks from youtrack (for my needs).
I can't promise, but if I have some free time, I will try to make it possible to import tasks from Jira, if someone does not do it before me))

**Comment by eL1fe** [comment]
@w3cproject 
still waiting for you haha

**Comment by sscarduzio** [comment]
![image](https://user-images.githubusercontent.com/1327189/154228488-462fb2b6-a325-4a26-b5f2-8035024048e5.png)

**Comment by dimart** [comment]
A basic version for Jira import has just landed:
https://github.com/JetBrains/space-issues-import#from-jira
We are working on expanding the import API for issues (like adding the ability to import custom fields) on Space side. 
Stay tuned!
