### ISSUE TITLE
Package not available

### ISSUE THREAD

**Issue by bellus93** [JetBrains/space-issues-import#8]
> Could not resolve org.jetbrains.youtrack:youtrack-rest-client:0.2.17.
         > Could not get resource 'https://jetbrains.bintray.com/youtrack-rest-client/org/jetbrains/youtrack/youtrack-rest-client/0.2.17/youtrack-rest-client-0.2.17.pom'.
            > Could not GET 'https://jetbrains.bintray.com/youtrack-rest-client/org/jetbrains/youtrack/youtrack-rest-client/0.2.17/youtrack-rest-client-0.2.17.pom'.

**Comment by dimart** [comment]
@bellus93 thanks for the report, we've just pushed an update that should fix it! 
Please try it, and if you have any other problem with the script, feel free to re-open the issue or create a new one.

cc @rafaavc
