### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Sidlegionair** [JetBrains/space-issues-import#9]
Hi,

When i try to execute the command from the readme I get the following error:
`Error: Main method not found in class com.jetbrains.space.import.MainKt, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
`
Command I'm trying to run:
`docker run public.registry.jetbrains.space/p/space/containers/space-issues-import:latest --youtrackServer https://youtrack.jetbrains.com --spaceServer **REDACTED** --spaceToken **REDACTED** --youtrackToken **REDACTED** --updateExistingIssues --replaceMissingStatus`

**Comment by dimart** [comment]
@Sidlegionair thanks a lot for reporting it!
The bug managed to escape from the tests in our CI/CD pipeline. 🤖

You can pull the fixed version like this: 
`docker pull public.registry.jetbrains.space/p/space/containers/space-issues-import:latest`
